[package]
name = "zenobox"
version = "0.2.9"
edition = "2024"
description = "Lightweight OCI Container Runtime & Docker Alternative in Rust"
license = "Apache-2.0"

[[bin]]
name = "zenobox"
path = "src/main.rs"

[lib]
name = "zenobox"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "fs", "sync", "signal", "process", "time"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = "0.7"
axum = { version = "0.8", features = ["macros", "multipart", "ws"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
portable-pty = "0.8"
tower = { version = "0.5", features = ["util"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls", "multipart"] }
flate2 = "1.0"
tar = "0.4"
futures-util = "0.3"
libc = "0.2"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"
zenocore = "0.2.3"
zeno-std = "0.2.3"
zenoengine = "0.2.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

